# Generated by Django 3.0.2 on 2021-05-23 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nick_name', models.CharField(max_length=100)),
                ('is_party_member', models.BooleanField(default=False)),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specie', to='api.Pokemon')),
            ],
            options={
                'db_table': 'pokemon_user',
            },
        ),
    ]
